### ISSUE TITLE
Error creating db

### ISSUE THREAD

**Issue by Lohoris** [flesh-cube/flesh-and-blood-cards#107]
While attempting to create the db I receive this enigmatic error:

```
connection to server at "localhost" (::1), port 3306 failed: received invalid response to SSL negotiation: X
```

Doesn't make a lot of sense to me because the credentials are correct, so dunno.

**Comment by luceleaftea** [comment]
Initial debugging questions I gotta ask: Are you attempting to connect to a Postgresql DB, and is it running? (Mine always turns off when I restart my computer and it gets me every time)

**Comment by Lohoris** [comment]
> Initial debugging questions I gotta ask: Are you attempting to connect to a Postgresql DB, and is it running? (Mine always turns off when I restart my computer and it gets me every time)

My bad, it was MariaDB. Dunno how I missed this.

**Comment by luceleaftea** [comment]
All good, glad you got it figured out!
