### ISSUE TITLE
Typo in Pedal to the Metal Card Name

### ISSUE THREAD

**Issue by R2Deakin** [flesh-cube/flesh-and-blood-cards#113]
Current csv has "Pedal to the Medal" instead of "Pedal to the Metal"

**Comment by R2Deakin** [comment]
Card number is ARC013 as I see that in most of the other issues posted

**Comment by luceleaftea** [comment]
Fixed in [v2.13.0](https://github.com/flesh-cube/flesh-and-blood-cards/releases/tag/v2.13.0) - thanks for making the fix!
