### ISSUE TITLE
MON-U does not have non-foil Fable

### ISSUE THREAD

**Issue by schubam** [flesh-cube/flesh-and-blood-cards#165]
No non-foil version for **MON000** (_Great Library of Solana_) exists in **MON-U.**

- https://www.cardmarket.com/en/FleshAndBlood/Cards/Great-Library-of-Solana/Versions
- https://fabtcg.com/collectors-centre/monarch/

In the TSV the value in `Variations` is
```
C - MON000 - F, S R - MON000 - U
```

It should be
```
C - MON000 - F, R - MON000 - U
```

**Comment by luceleaftea** [comment]
Thank you so much for your detailed bug report! This is fixed in [v4.2.1](https://github.com/the-fab-cube/flesh-and-blood-cards/releases/tag/v4.2.1).
